#!/usr/bin/env python3
"""Generate SDRTrunk category sub-streams + talkgroup-label aliases from the TSV.

Reads moswin_talkgroups.tsv (TGID <tab> label <tab> group) and rewrites two
marker-delimited regions of a v4 SDRTrunk playlist:

  <!-- STREAMS:BEGIN --> ... <!-- STREAMS:END -->       (Icecast <stream> mounts)
  <!-- TALKGROUPS:BEGIN --> ... <!-- TALKGROUPS:END -->  (named <alias> entries)

Streams: one "MOSWIN All" mount (/ems.mp3, carries everything) plus one mount
per distinct group, e.g. group "Fire" -> stream "MOSWIN Fire", mount /ems-fire.mp3.
Each <stream> is cloned from the playlist's existing <stream> so the exact format
+ Icecast password/host/port are preserved (nothing secret lives in this script).

Aliases: a catch-all (all talkgroups -> All stream, recorded) plus one per TSV row
that routes to BOTH the All stream and its group's stream and records playable
audio. So /ems.mp3 = everything; /ems-<group>.mp3 = just that category.

Usage:
  python3 gen_aliases.py <playlist.xml> [moswin_talkgroups.tsv]

Channel config is left untouched.
"""
import os
import re
import sys
from xml.sax.saxutils import quoteattr

A_BEGIN = '<!-- TALKGROUPS:BEGIN (generated from p25/moswin_talkgroups.tsv by gen_aliases.py — edit the TSV, not here) -->'
A_END = '<!-- TALKGROUPS:END -->'
S_BEGIN = '<!-- STREAMS:BEGIN (generated by gen_aliases.py — one mount per talkgroup group) -->'
S_END = '<!-- STREAMS:END -->'
LIST = "MOSWIN"
ALL = "All"  # the catch-all category / "MOSWIN All" stream on /ems.mp3

COLORS = {
    "fire": -65536, "ems": -23296, "police": -16776961,
    "interop": -16711936, "local": -6710887,
}
DEFAULT_COLOR = -1

# Fallback <stream> used only if the playlist has none yet (fresh template).
_DEFAULT_STREAM = (
    '<stream type="icecastHTTPConfiguration" '
    'xmlns:wstxns1="http://www.w3.org/2001/XMLSchema-instance" wstxns1:type="ICECAST_HTTP" '
    'sample_rate="8000" user_name="source" bitrate="32" channels="1" mount_point="/ems.mp3" '
    'public="false" inline="false" delay="0" host="localhost" port="8000" enabled="true" '
    'password="CHANGE_ME" maximum_recording_age="600000" name="MOSWIN Live">\n'
    '    <format>MP3</format>\n  </stream>'
)


def slug(group):
    return re.sub(r"[^a-z0-9]+", "-", group.lower()).strip("-")


def stream_name(group):
    return f"MOSWIN {group}"


def mount(group):
    return "/ems.mp3" if group == ALL else f"/ems-{slug(group)}.mp3"


def read_tsv(path):
    rows, groups = [], []
    with open(path) as f:
        for raw in f:
            line = raw.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 2 or not parts[0].strip().isdigit():
                continue
            tgid = parts[0].strip()
            label = parts[1].strip()
            group = parts[2].strip() if len(parts) > 2 and parts[2].strip() else "Local"
            rows.append((tgid, label, group))
            if group not in groups:
                groups.append(group)
    return rows, groups


def build_streams(base_stream, groups):
    out = [S_BEGIN]
    for cat in [ALL] + groups:
        s = base_stream
        s = re.sub(r'\bname="[^"]*"', f'name={quoteattr(stream_name(cat))}', s)
        s = re.sub(r'mount_point="[^"]*"', f'mount_point="{mount(cat)}"', s)
        s = re.sub(r'maximum_recording_age="[^"]*"', 'maximum_recording_age="600000"', s)
        s = re.sub(r'\benabled="[^"]*"', 'enabled="true"', s)
        out.append("  " + s)
    out.append(S_END)
    return "\n".join(out)


def alias(name, color, ids):
    lines = [f'  <alias color="{color}" group="" name={quoteattr(name)} list="{LIST}">']
    lines += [f'    {i}' for i in ids]
    lines.append('  </alias>')
    return "\n".join(lines)


def bc(cat):
    return f'<id type="broadcastChannel" channel={quoteattr(stream_name(cat))}/>'


def build_aliases(rows):
    out = [A_BEGIN]
    out.append(alias("Cape County All", -16711936, [
        '<id type="talkgroupRange" protocol="APCO25" min="0" max="65535"/>',
        bc(ALL), '<id type="record"/>',
    ]))
    for tgid, label, group in rows:
        out.append(alias(label, COLORS.get(group.lower(), DEFAULT_COLOR), [
            f'<id type="talkgroup" value="{tgid}" protocol="APCO25"/>',
            bc(ALL), bc(group), '<id type="record"/>',
        ]))
    out.append(A_END)
    return "\n".join(out)


def replace_region(text, begin, end, block, *, before_close="</playlist>"):
    if begin in text and end in text:
        return re.sub(re.escape(begin) + r".*?" + re.escape(end), block, text, flags=re.DOTALL)
    return text.replace(before_close, block + "\n" + before_close, 1)


def main():
    if len(sys.argv) < 2:
        sys.exit(f"usage: {sys.argv[0]} <playlist.xml> [moswin_talkgroups.tsv]")
    playlist = sys.argv[1]
    tsv = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "moswin_talkgroups.tsv")

    rows, groups = read_tsv(tsv)
    s = open(playlist).read()

    # Grab the existing <stream> as the format/credentials template, then drop
    # all bare streams/aliases not already inside our markers.
    m = re.search(r"<stream\b.*?</stream>", s, flags=re.DOTALL)
    base_stream = m.group(0) if m else _DEFAULT_STREAM
    if A_BEGIN not in s:
        s = re.sub(r"[ \t]*<alias\b.*?</alias>\s*", "", s, flags=re.DOTALL)
    if S_BEGIN not in s:
        s = re.sub(r"[ \t]*<stream\b.*?</stream>\s*", "", s, flags=re.DOTALL)

    s = replace_region(s, S_BEGIN, S_END, build_streams(base_stream, groups))
    s = replace_region(s, A_BEGIN, A_END, build_aliases(rows))

    tmp = playlist + ".tmp"
    with open(tmp, "w") as f:
        f.write(s)
    os.replace(tmp, playlist)
    print(f"wrote {len(groups)+1} streams (All + {', '.join(groups)}) and "
          f"{len(rows)} talkgroup aliases into {playlist}")


if __name__ == "__main__":
    main()
